# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [2]:
nll = np.zeros(10)
print("Null Vector = ",nll)

Null Vector =  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3. Create a vector with values ranging from 10 to 49

In [3]:
rng = np.arange(10,50)
print("Numpy range = ",rng)

Numpy range =  [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


4. Find the shape of previous array in question 3

In [4]:
print("Shape of question 3 = ",rng.shape)

Shape of question 3 =  (40,)


5. Print the type of the previous array in question 3

In [5]:
print("Type of question 3 = ",rng.dtype)

Type of question 3 =  int32


6. Print the numpy version and the configuration


In [6]:
print("Version = ",np.__version__)
print("Config = ",np.show_config())

Version =  1.19.2
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Oye Zaini/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Oye Zaini/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Oye Zaini/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Oye Zaini/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Oye Zaini/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Oye Zaini/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Oye Zaini/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Oye Zaini/anaconda3\\Library\\include']
Co

7. Print the dimension of the array in question 3


In [7]:
print("Dimensions of question 3 = ",rng.ndim)

Dimensions of question 3 =  1


8. Create a boolean array with all the True values

In [8]:
bol = np.array([1,2,3,4,5], dtype = bool)
print("Boolean values = ",bol)

Boolean values =  [ True  True  True  True  True]


9. Create a two dimensional array




In [9]:
a = [[1,2,3,4,5],[6,7,8,9,10]]
two_dim = np.array(a)
print(two_dim)
print("Dimensions are = ",two_dim.ndim)
print("Shape is = ",two_dim.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Dimensions are =  2
Shape is =  (2, 5)


10. Create a three dimensional array

In [10]:
b = [[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]]
three_dim = np.array(b)
print(three_dim)
print("Dimensions are = ",three_dim.ndim)
print("Shape is = ",three_dim.shape)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]]
Dimensions are =  3
Shape is =  (1, 3, 5)


Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [11]:
rng = np.arange(10,50)
print("before = ",rng)
print("Reverse = ",rng[::-1])

before =  [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
Reverse =  [49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


12. Create a null vector of size 10 but the fifth value which is 1 

In [12]:
nul = np.zeros(10)
print("before = ",nul)
nul[4] = 1
print("after = ",nul)

before =  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
after =  [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


13. Create a 3x3 identity matrix

In [13]:
iden = np.identity(3)
print("3x3 identity matrix = ",iden)

3x3 identity matrix =  [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [14]:
arr = np.array([1, 2, 3, 4, 5], dtype = float)
print(arr)
print("Type from int to float = ",arr.dtype)

[1. 2. 3. 4. 5.]
Type from int to float =  float64


15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [15]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
mul = arr1 * arr2
print("Multiplication of arrays = ",mul)

Multiplication of arrays =  [[ 0.  8.  3.]
 [28. 10. 72.]]


16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [16]:
arr1 = np.array([[1., 2., 3.], [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
compare = arr1 == arr2
print("comparison b/w 2 arrays = ",compare)

comparison b/w 2 arrays =  [[False False False]
 [False False False]]


17. Extract all odd numbers from arr with values(0-9)

In [17]:
odd = np.arange(0,10)
print("Range is = ",odd)
print("Odd values are = ",odd[odd % 2 != 0])

Range is =  [0 1 2 3 4 5 6 7 8 9]
Odd values are =  [1 3 5 7 9]


18. Replace all odd numbers to -1 from previous array

In [18]:
odd = np.arange(0,10)
print("Range is = ",odd)
print("Odd values are = ",odd[odd % 2 != 0])
odd[odd % 2 != 0] = -1
print("Replacing odd values to -1 = ",odd)

Range is =  [0 1 2 3 4 5 6 7 8 9]
Odd values are =  [1 3 5 7 9]
Replacing odd values to -1 =  [ 0 -1  2 -1  4 -1  6 -1  8 -1]


19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [19]:
arr = np.arange(10)
print("before = ",arr)
arr[[5,6,7,8]] = 12
print("change indexing = ",arr)

before =  [0 1 2 3 4 5 6 7 8 9]
change indexing =  [ 0  1  2  3  4 12 12 12 12  9]


20. Create a 2d array with 1 on the border and 0 inside

In [20]:
_2d_array = np.ones((4,4))
print("Before = ",_2d_array)
_2d_array[1:-1,1:-1] = 0
print("After = ",_2d_array)

Before =  [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
After =  [[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [21]:
arr2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
arr2d[1,1] = 12
print("5th values is replaced by = ",arr2d)

5th values is replaced by =  [[ 1  2  3]
 [ 4 12  6]
 [ 7  8  9]]


22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [22]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0,0] = 64
print("1st array's value = ",arr3d)

1st array's value =  [[[64 64 64]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [23]:
arr = np.arange(0,10).reshape(2,5)
print("Array = ",arr)
arr[0]

Array =  [[0 1 2 3 4]
 [5 6 7 8 9]]


array([0, 1, 2, 3, 4])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [24]:
arr = np.arange(0,10).reshape(2,5)
print("Array is =",arr)
print("2nd value of 2nd 1-D array is = ",arr[1,1])

Array is = [[0 1 2 3 4]
 [5 6 7 8 9]]
2nd value of 2nd 1-D array is =  6


25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [25]:
arr = np.arange(0,10).reshape(2,5)
print("Array is = ",arr)
arr[:,2]

Array is =  [[0 1 2 3 4]
 [5 6 7 8 9]]


array([2, 7])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [26]:
arr10 = np.random.rand(100).reshape(10,10)
print(arr10)
print("Mini value = ",np.amin(arr10))
print("Max value = ",np.amax(arr10))

[[0.03067921 0.02091518 0.26539959 0.286253   0.4910538  0.97114647
  0.64908157 0.3160817  0.74686965 0.49634166]
 [0.50228026 0.51493169 0.65036205 0.40421384 0.88627798 0.04381988
  0.50598177 0.12753143 0.82330296 0.92936109]
 [0.27556827 0.56198882 0.69084451 0.60830378 0.53086367 0.0339278
  0.34005786 0.01030551 0.68270673 0.87950419]
 [0.2787315  0.98484725 0.89153455 0.04075311 0.83361923 0.98482499
  0.30975475 0.20810171 0.13032018 0.49271944]
 [0.61819375 0.36347226 0.45051219 0.78694031 0.89176895 0.46628244
  0.70349258 0.60677011 0.28027641 0.78746951]
 [0.8919571  0.4382967  0.71051288 0.84199824 0.39552299 0.15494894
  0.54197211 0.29486491 0.75503358 0.46205576]
 [0.09294294 0.87715126 0.71535376 0.82238309 0.87632834 0.04074667
  0.61721066 0.4910176  0.88213216 0.07969863]
 [0.69512165 0.51704333 0.61777018 0.81846698 0.30059326 0.08847697
  0.20016399 0.40975749 0.88042453 0.69576494]
 [0.87453588 0.91119507 0.23556568 0.78420038 0.27868567 0.83546666
  0.29496438 

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [27]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
c = np.intersect1d(a,b)
print("common items = ",c)

common items =  [2 4]


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [28]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.sort(a))
print(np.sort(b))
c = np.intersect1d(a,b)
print(c)
print(np.searchsorted(a,c))

[1 2 2 3 3 3 4 4 5 6]
[ 2  2  4  4  7  7  8  9  9 10]
[2 4]
[1 5]


29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [29]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
print(data)
name = names != 'Will'
print('==================================================')
print(data[name])

[[-1.50379946 -0.89003758 -1.00073291  1.47952343]
 [-1.16606525 -0.04767486  0.08806049  0.16843714]
 [-0.08731312 -1.66227651 -0.67130746 -0.0498193 ]
 [ 0.33541298  1.16838119 -0.12255236 -0.3947758 ]
 [-0.67973008  0.45441155  0.40295975  0.12323361]
 [ 0.99322983 -1.13820141  0.07223718 -0.10256419]
 [ 0.22475613  2.03312383 -0.08450576 -0.40453434]]
[[-1.50379946 -0.89003758 -1.00073291  1.47952343]
 [-1.16606525 -0.04767486  0.08806049  0.16843714]
 [ 0.33541298  1.16838119 -0.12255236 -0.3947758 ]
 [ 0.99322983 -1.13820141  0.07223718 -0.10256419]
 [ 0.22475613  2.03312383 -0.08450576 -0.40453434]]


30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [30]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
print(data)
nam = (names != 'Will') & (names != 'Joe')
print("==================================================")
print(data[nam])

[[ 0.24773172 -0.56813505  0.23880331 -1.03478397]
 [-0.26393254  0.26063961  2.82406272 -0.39685691]
 [ 0.84967183  0.73620493  1.38093501 -0.45035321]
 [ 0.98628546 -0.29013389 -1.11497719  0.15191912]
 [-1.18964516  0.63852905  0.26932152 -0.73242578]
 [-0.17967482  0.9029671  -0.18020811 -0.41680617]
 [ 0.82017958  0.69613139  2.02256039 -0.8289812 ]]
[[ 0.24773172 -0.56813505  0.23880331 -1.03478397]
 [ 0.98628546 -0.29013389 -1.11497719  0.15191912]]


Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [31]:
rand_arr = np.random.uniform(1,15, size = (5,3)) 
print(rand_arr)

[[ 5.232081   11.7589228  10.50785614]
 [ 3.12547564 13.35562375 14.95237065]
 [ 8.55402621 12.06775566  5.45734139]
 [12.14298723  5.00847187  1.89953286]
 [ 5.41685534 13.40507688  5.05963493]]


32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [32]:
rand_arrr = np.random.uniform(1,16, size = (2,2,4))
print(rand_arrr)

[[[15.34197643  4.73255766 13.9461083   7.70734325]
  [ 6.64285706  8.84760687  7.61039587  2.24508588]]

 [[ 1.90928174 15.82800521 15.90821834  3.91067513]
  [ 3.39350803  4.13464524  5.78593664 13.67133511]]]


33. Swap axes of the array you created in Question 32

In [33]:
rand_arrr = np.random.uniform(1,16, size = (2,2,4))
print("Original array = ",rand_arrr)
print("====================================================")
print("Transpose of array = ",np.transpose(rand_arrr))

Original array =  [[[ 7.05803643 12.78915324  3.12621416 14.91870706]
  [14.29191564  7.40334089 15.90821002  8.11258014]]

 [[ 3.52335247  3.22438404  4.28515643  6.83472376]
  [ 9.57589187  6.12965389 11.59066101  9.11745313]]]
Transpose of array =  [[[ 7.05803643  3.52335247]
  [14.29191564  9.57589187]]

 [[12.78915324  3.22438404]
  [ 7.40334089  6.12965389]]

 [[ 3.12621416  4.28515643]
  [15.90821002 11.59066101]]

 [[14.91870706  6.83472376]
  [ 8.11258014  9.11745313]]]


34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [34]:
arr = np.random.uniform(0,20, size = (10))
arr = arr.astype('int32') 
arr = np.sqrt(arr)
arr = np.where(arr < 0.5, 0, arr)
arr = arr.astype('int32')
print(arr)

[4 0 3 3 4 1 2 3 3 3]


35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [35]:
arr1 = np.random.uniform(0,20, size = (10))
arr2 = np.random.uniform(0,20, size = (10))
arr3 = np.maximum(arr1,arr2)
print("Random values of arr1 = ",arr1)
print("=========================================")
print("Random values of arr2 = ",arr2)
print("=========================================")
print("Maximum values = ",arr3)

Random values of arr1 =  [ 1.55610099 12.01550368 11.69287927  2.27318369 11.02865726 18.59774796
  3.00251849 13.77502185 19.91478152 11.09361069]
Random values of arr2 =  [12.49164272  1.77712987  6.81814839 15.66783781  8.69596182 11.05596669
 12.00032531 13.58846065  3.38715964  7.18568202]
Maximum values =  [12.49164272 12.01550368 11.69287927 15.66783781 11.02865726 18.59774796
 12.00032531 13.77502185 19.91478152 11.09361069]


36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [36]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
sort = np.sort(names)
print("Sorted = ",sort)
print("========================")
unique = np.unique(names)
print("unique names = ",unique)

Sorted =  ['Bob' 'Bob' 'Joe' 'Joe' 'Joe' 'Will' 'Will']
unique names =  ['Bob' 'Joe' 'Will']


37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [37]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
c = np.setdiff1d(a,b)
print(c)

[1 2 3 4]


38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [38]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])
sampleArray = np.delete(sampleArray,2, axis = 1)
sampleArray = np.insert(sampleArray,2,newColumn, axis = 1)
print(sampleArray)

[[34 43 10]
 [82 22 10]
 [53 94 10]]


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [39]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
z = np.dot(x,y)
print(z)

[[ 28.  64.]
 [ 67. 181.]]


40. Generate a matrix of 20 random values and find its cumulative sum

In [40]:
arr = np.random.uniform(1,20, size = (4,5))
arr = arr.astype('int32')
print(arr.cumsum())

[ 17  25  42  59  63  64  67  81  95 102 104 122 132 141 142 157 166 183
 199 200]
